name: myspace_core
description: "MySpace Core"
version: 0.0.1
homepage: www.shoh.dev

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  redux: ^5.0.0
  flutter_redux: ^0.10.0

  get_it: ^8.0.3
  intl: ^0.20.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: